### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by coldfix** [blogdown/blogdown#3]
Hey,

How do you feel about adding the capability to load additional modules as plugins? The existence of `blogdown/modules/add_module_path` seems to indicate that this was planned at some point at least.

I'd suggest something like this:

- add config entry `module_folders` defaulting to `_modules/` (or "plugin", i.d.c.)
- use [runpy.run_path](https://docs.python.org/2.7/library/runpy.html#runpy.run_path) to load plugin modules from configured pathes
- store loaded modules in a dict

Alternatives to using runpy, which I think won't be as simple / clean / extensible (either or all):
- make `blogdown.modules` a namespace package which is extended by entries in `config.module_folders`
- use setuptools entry points for plugins and allow to extend the `pkg_resources.working_set` with some config entry.
- something like `try: __import__('plugins.'+name); except ImportError: __import__('blogdown.modules.'+name)`

What do you think?

**EDIT:** By the way, my use case is that I'm considering to add a lightweight commenting system that doesn't rely on external services.

Note about entry points: maybe this isn't such a bad idea after all. It would allow to also use installed plugins rather than source files just dropped in a local directory.

Of course, I'd be willing to do the work, if you don't have time.

**Comment by yangyubo** [comment]
@coldfix Great idea! And please go ahead, I'll merge your PR and push a new PyPI release.
